
name: CircleCI
on:
  workflow_call:

jobs:
  initialize:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Create circleci config.yml
        uses: actions/checkout@v3
        with:
          repository: next-escape/circleci-config
          path: .circleci
