# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Release
on:
  workflow_call:
    inputs:
      IS_RELEASE:
        type: boolean
        description: Perform a release. Upgrade the version
        required: true
        default: false
      IS_PUBLISH:
        type: boolean
        description: Publish the release
        required: true
        default: false
      GITHUB_REPO:
        type: string
        description: Repository to use
        required: true
        default: ''
  workflow_dispatch:
    inputs:
      IS_RELEASE:
        type: boolean
        description: Perform a release. Upgrade the version
        required: true
        default: false
      IS_PUBLISH:
        type: boolean
        description: Publish the release
        required: true
        default: false

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Release
        uses: indiesdev/curl@v1.1
        with:
          url: https://circleci.com/api/v2/project/gh/next-escape/${{ github.event.inputs.GITHUB_REPO }}/pipeline
          method: "POST"
          accept: 200, 201, 204
          headers: "{ \"Circle-Token\": ${{ secrets.CIRCLE_TOKEN }}, \"Content-Type\": application/json }"
          body: '{ "branch": "${{ github.ref_name }}",  "parameters": { "IS_RELEASE": ${{ github.event.inputs.IS_RELEASE }}, "IS_PUBLISH": ${{ github.event.inputs.IS_PUBLISH }}  } }'
          log-response: true
