name: Release a repository
on:
  workflow_dispatch:
    inputs:
      IS_RELEASE:
        type: boolean
        description: Perform a release. Upgrade the version
        required: true
        default: false
      IS_PUBLISH:
        type: boolean
        description: Publish the release
        required: true
        default: false
      RELEASE_REPO:
        type: choice
        description: Repository to use
        required: true
        options:
          - next-escape-api
          - next-escape-data
          - next-escape-model
      RELEASE_BRANCH:
        type: string
        description: Branch to perform the release
        required: false
        default: main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Release
        uses: indiesdev/curl@v1.1
        with:
          url: https://circleci.com/api/v2/project/gh/next-escape/${{ github.event.inputs.RELEASE_REPO }}/pipeline
          method: "POST"
          accept: 200, 201, 204
          headers: "{ \"Circle-Token\": ${{ secrets.CIRCLE_TOKEN }}, \"Content-Type\": application/json }"
          body: '{ "branch": "${{ github.event.inputs.RELEASE_BRANCH }}", "parameters": { "IS_RELEASE": ${{ github.event.inputs.IS_RELEASE }}, "IS_PUBLISH": ${{ github.event.inputs.IS_PUBLISH }}  } }'
          log-response: true
